version: 2
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node8:
          filters: &all_commits
            tags:
              only: /.*/
      - lint:
          requires:
            - node8
          filters: *all_commits
      - tests:
          requires:
            - lint
          filters: &master_and_releases
            branches:
              only: master
            tags: &releases
              only: '/^v[\d.]+$/'
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs
jobs:
  node8:
    docker:
      - image: 'node:8'
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &npm_install_and_link
          name: Install and link the module
          command: |-
            mkdir -p /home/node/.npm-global
            ./.circleci/npm-install-retry.js
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run: npm test
  lint:
    docker:
      - image: 'node:8'
        user: node
    steps:
      - checkout
      - run: *npm_install_and_link
      - run:
          name: Run linting.
          command: npm run lint
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
